version: '3.1'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1

  tc-backend:
    container_name: tc-backend
    build: .
    restart: always
    volumes:
      - ./static:/app/static
      - ./docker/conf:/app/conf/
      - ./media:/app/media
    ports:
      - "8081:8000"
    depends_on:
      - mysql
#    env_file:
#          - .env
    environment:
      - GUNICORN_CMD_ARGS="--workers=3"

  tc-front:
    container_name: tc-front
    image:  tc-front:v2
    restart: always
    ports:
      - "5000:80"